using System;

public enum DestructibleId
{
	NONE,
	IDOL_SPELL_IDOL_OF_BLOOD,
	IDOL_SPELL_IDOL_OF_BLOOD_MSTR,
	IDOL_SPELL_IDOL_OF_CHANGE,
	IDOL_SPELL_IDOL_OF_CHANGE_MSTR,
	IDOL_SPELL_IDOL_OF_PESTILENCE,
	IDOL_SPELL_IDOL_OF_PESTILENCE_MSTR,
	IDOL_SPELL_IDOL_OF_LUST,
	IDOL_SPELL_IDOL_OF_LUST_MSTR,
	IDOL_SKILL_PYRE_OF_THE_RIGHTEOUS,
	IDOL_CAMPAIGN_WH_03,
	IDOL_SPELL_IDOL_OF_DEATH,
	IDOL_SPELL_IDOL_OF_DEATH_MSTR,
	IDOL_CAMP_UNDEAD_08,
	MAX_VALUE
}
