using System;

public enum PopupModuleId
{
	NONE,
	POPUP_GENERIC_ANCHOR,
	POPUP_SCOUT,
	POPUP_SCOUTED_MISSION,
	POPUP_CONFIRM_MISSION,
	POPUP_SEND_SHIPMENT_REQUEST,
	POPUP_SEND_SHIPMENT,
	POPUP_SHIPMENT_LATE,
	POPUP_NEW_SHIPMENT_REQUEST
}
