using System;

public enum ProcWarbandRankId
{
	NONE,
	PROC_WARBAND_RANK_0_A,
	PROC_WARBAND_RANK_1_A,
	PROC_WARBAND_RANK_2_A,
	PROC_WARBAND_RANK_3_A,
	PROC_WARBAND_RANK_4_A,
	PROC_WARBAND_RANK_4_B,
	PROC_WARBAND_RANK_5_A,
	PROC_WARBAND_RANK_5_B,
	PROC_WARBAND_RANK_6_A,
	PROC_WARBAND_RANK_6_B,
	PROC_WARBAND_RANK_7_A,
	PROC_WARBAND_RANK_7_B,
	PROC_WARBAND_RANK_8_A,
	PROC_WARBAND_RANK_8_B,
	PROC_WARBAND_RANK_9_A,
	PROC_WARBAND_RANK_9_B,
	PROC_WARBAND_RANK_10_A,
	PROC_WARBAND_RANK_10_B,
	PROC_WARBAND_RANK_0_B = 20,
	PROC_WARBAND_RANK_1_B,
	PROC_WARBAND_RANK_2_B,
	PROC_WARBAND_RANK_3_B,
	MAX_VALUE
}
