using System;

public enum TrapTypeId
{
	NONE,
	PILLAR_DECOR = 2,
	MADSTUFF_WALL,
	MADSTUFF_BORDER,
	SKAVEN_FLOOR,
	MANTICORE_ACID,
	SKILL_WYRDSTONE_LURE = 10,
	SKILL_WYRDSTONE_LURE_MSTR,
	SKILL_BLACK_POWDER_TRAP,
	SKILL_WHITE_POWDER_TRAP,
	SKILL_DEATH_TRAP,
	SKILL_DEATH_TRAP_MSTR,
	SKILL_EYE_SEE_YOU,
	SKILL_EYE_SEE_YOU_MSTR,
	MAX_VALUE
}
