using System;

public enum TrapEffectId
{
	TRAP_HOUSE_CORNER_1 = 2,
	TRAP_MADSTUFF_BORDER_1,
	TRAP_MADSTUFF_WALL_1,
	TRAP_SKAVEN_POISON_1,
	TRAP_MANTICORE_ACID_1,
	TRAP_SKAVEN_POISON_2,
	TRAP_SKAVEN_POISON_3,
	TRAP_MADSTUFF_BORDER_2,
	TRAP_MADSTUFF_BORDER_3,
	TRAP_MADSTUFF_BORDER_4,
	TRAP_MADSTUFF_WALL_2,
	TRAP_MADSTUFF_WALL_3,
	TRAP_MADSTUFF_WALL_4,
	TRAP_HOUSE_CORNER_2,
	TRAP_HOUSE_CORNER_3,
	TRAP_SKILL_BLACK_POWDER_TRAP = 18,
	TRAP_SKILL_WHITE_POWDER_TRAP,
	TRAP_SKILL_WYRDSTONE_LURE,
	TRAP_SKILL_WYRDSTONE_LURE_MSTR,
	TRAP_SKILL_DEATH_TRAP,
	TRAP_SKILL_DEATH_TRAP_MSTR,
	TRAP_EYE_SEE_YOU = 25,
	TRAP_EYE_SEE_YOU_MSTR,
	MAX_VALUE
}
