using System;

public enum TrapId
{
	NONE,
	TRAPS_PILLAR_DECOR_01 = 3,
	TRAPS_PILLAR_DECOR_02,
	TRAPS_PILLAR_DECOR_03,
	TRAPS_PILLAR_DECOR_04,
	TRAPS_PILLAR_DECOR_05,
	TRAPS_PILLAR_DECOR_06,
	TRAPS_MADSTUFF_WALL_01,
	TRAPS_MADSTUFF_WALL_02,
	TRAPS_MADSTUFF_WALL_03,
	TRAPS_MADSTUFF_WALL_04,
	TRAPS_MADSTUFF_WALL_05,
	TRAPS_MADSTUFF_WALL_06,
	TRAPS_MADSTUFF_WALL_07,
	TRAPS_MADSTUFF_WALL_08,
	TRAPS_MADSTUFF_BORDER_01 = 18,
	TRAPS_MADSTUFF_BORDER_02,
	TRAP_SKAVEN_01,
	MANTICORE_ACID,
	TRAP_SKILL_WYRDSTONE_LURE,
	TRAP_SKILL_BLACK_POWDER_TRAP,
	TRAP_SKILL_WHITE_POWDER_TRAP,
	TRAP_SKILL_WYRDSTONE_LURE_MSTR,
	TRAP_SKILL_DEATH_TRAP,
	TRAP_SKILL_DEATH_TRAP_MSTR,
	TRAP_SKILL_EYE_SEE_YOU,
	TRAP_SKILL_EYE_SEE_YOU_MSTR,
	MAX_VALUE
}
