using System;

public enum WarbandContactId
{
	NONE,
	ALCHEMIST = 2,
	ALCHEMIST_MSTR,
	ARMORER,
	ARMORER_MSTR,
	ARMORER_APPRENTICE,
	ARMORER_APPRENTICE_MSTR,
	LEATHERWORKER,
	LEATHERWORKER_MSTR,
	TAILOR,
	TAILOR_MSTR,
	BOWYER,
	BOWYER_MSTR,
	GUNSMITH,
	GUNSMITH_MSTR,
	MERCHANT,
	MERCHANT_MSTR,
	WEAPONSMITH,
	WEAPONSMITH_MSTR,
	GREAT_WEAPONSMITH,
	GREAT_WEAPONSMITH_MSTR,
	ENCHANTER,
	ENCHANTER_MSTR,
	ENCHANTER_MSTR_MSTR,
	MAX_VALUE
}
