using System;

public enum WyrdstoneId
{
	WYRDSTONE_DIS_00_OUTDOOR_LARGE_01 = 1,
	WYRDSTONE_DIS_00_OUTDOOR_MEDIUM_01,
	WYRDSTONE_DIS_00_OUTDOOR_SMALL_01,
	WYRDSTONE_DIS_00_INDOOR_LARGE_01,
	WYRDSTONE_DIS_00_INDOOR_MEDIUM_01,
	WYRDSTONE_DIS_00_INDOOR_SMALL_01,
	MAX_VALUE
}
